# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae78f7b75f6ecac480ca76c809c24a78855ebb4b00020c102aaf6714169d252627ff93fc755ad4487c0180cc3772bb126165e58985912e28017ee7248e648899

test:
  secret_key_base: 6f3404dc867cc89a44d2b58baef9a3446d8e07710ee292f32ac961c86e54799b85eaa2e2a94ee55af71e186d304b9c2c1751a37efbec315bd9ea4483db57721a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
